/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashbookRouteImport } from './routes/cashbook'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as KhataRouteImport } from './routes/khata'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as KhataIndexRouteImport } from './routes/khata.index'
import { Route as KhataIdRouteImport } from './routes/khata.$id'
import { Route as PurchasesIndexRouteImport } from './routes/purchases.index'
import { Route as PurchasesIdRouteImport } from './routes/purchases.$id'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesIdRouteImport } from './routes/sales.$id'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as SalesQuickRouteImport } from './routes/sales.quick'
import { Route as StockIndexRouteImport } from './routes/stock.index'
import { Route as StockIdRouteImport } from './routes/stock.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbookRoute = CashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataRoute = KhataRouteImport.update({
  id: '/khata',
  path: '/khata',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const KhataIndexRoute = KhataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KhataRoute,
} as any)
const KhataIdRoute = KhataIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KhataRoute,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasesRoute,
} as any)
const PurchasesIdRoute = PurchasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchasesRoute,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesRoute,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesRoute,
} as any)
const SalesQuickRoute = SalesQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => SalesRoute,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockRoute,
} as any)
const StockIdRoute = StockIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StockRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashbook': typeof CashbookRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/khata': typeof KhataRouteWithChildren
  '/more': typeof MoreRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
  '/khata/$id': typeof KhataIdRoute
  '/purchases/$id': typeof PurchasesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/quick': typeof SalesQuickRoute
  '/stock/$id': typeof StockIdRoute
  '/employees/': typeof EmployeesIndexRoute
  '/khata/': typeof KhataIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashbook': typeof CashbookRoute
  '/expenses': typeof ExpensesRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/khata/$id': typeof KhataIdRoute
  '/purchases/$id': typeof PurchasesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/quick': typeof SalesQuickRoute
  '/stock/$id': typeof StockIdRoute
  '/employees': typeof EmployeesIndexRoute
  '/khata': typeof KhataIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/sales': typeof SalesIndexRoute
  '/stock': typeof StockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashbook': typeof CashbookRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/khata': typeof KhataRouteWithChildren
  '/more': typeof MoreRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
  '/khata/$id': typeof KhataIdRoute
  '/purchases/$id': typeof PurchasesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/quick': typeof SalesQuickRoute
  '/stock/$id': typeof StockIdRoute
  '/employees/': typeof EmployeesIndexRoute
  '/khata/': typeof KhataIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashbook'
    | '/employees'
    | '/expenses'
    | '/khata'
    | '/more'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/search'
    | '/settings'
    | '/stock'
    | '/employees/$id'
    | '/khata/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quick'
    | '/stock/$id'
    | '/employees/'
    | '/khata/'
    | '/purchases/'
    | '/sales/'
    | '/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashbook'
    | '/expenses'
    | '/more'
    | '/reports'
    | '/search'
    | '/settings'
    | '/employees/$id'
    | '/khata/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quick'
    | '/stock/$id'
    | '/employees'
    | '/khata'
    | '/purchases'
    | '/sales'
    | '/stock'
  id:
    | '__root__'
    | '/'
    | '/cashbook'
    | '/employees'
    | '/expenses'
    | '/khata'
    | '/more'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/search'
    | '/settings'
    | '/stock'
    | '/employees/$id'
    | '/khata/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quick'
    | '/stock/$id'
    | '/employees/'
    | '/khata/'
    | '/purchases/'
    | '/sales/'
    | '/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashbookRoute: typeof CashbookRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  KhataRoute: typeof KhataRouteWithChildren
  MoreRoute: typeof MoreRoute
  PurchasesRoute: typeof PurchasesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbook': {
      id: '/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof CashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata': {
      id: '/khata'
      path: '/khata'
      fullPath: '/khata'
      preLoaderRoute: typeof KhataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/khata/': {
      id: '/khata/'
      path: '/'
      fullPath: '/khata/'
      preLoaderRoute: typeof KhataIndexRouteImport
      parentRoute: typeof KhataRoute
    }
    '/khata/$id': {
      id: '/khata/$id'
      path: '/$id'
      fullPath: '/khata/$id'
      preLoaderRoute: typeof KhataIdRouteImport
      parentRoute: typeof KhataRoute
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/purchases/$id': {
      id: '/purchases/$id'
      path: '/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof PurchasesIdRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/quick': {
      id: '/sales/quick'
      path: '/quick'
      fullPath: '/sales/quick'
      preLoaderRoute: typeof SalesQuickRouteImport
      parentRoute: typeof SalesRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/$id': {
      id: '/stock/$id'
      path: '/$id'
      fullPath: '/stock/$id'
      preLoaderRoute: typeof StockIdRouteImport
      parentRoute: typeof StockRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface KhataRouteChildren {
  KhataIdRoute: typeof KhataIdRoute
  KhataIndexRoute: typeof KhataIndexRoute
}

const KhataRouteChildren: KhataRouteChildren = {
  KhataIdRoute: KhataIdRoute,
  KhataIndexRoute: KhataIndexRoute,
}

const KhataRouteWithChildren = KhataRoute._addFileChildren(KhataRouteChildren)

interface PurchasesRouteChildren {
  PurchasesIdRoute: typeof PurchasesIdRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
}

const PurchasesRouteChildren: PurchasesRouteChildren = {
  PurchasesIdRoute: PurchasesIdRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
}

const PurchasesRouteWithChildren = PurchasesRoute._addFileChildren(
  PurchasesRouteChildren,
)

interface SalesRouteChildren {
  SalesIdRoute: typeof SalesIdRoute
  SalesNewRoute: typeof SalesNewRoute
  SalesQuickRoute: typeof SalesQuickRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesIdRoute: SalesIdRoute,
  SalesNewRoute: SalesNewRoute,
  SalesQuickRoute: SalesQuickRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface StockRouteChildren {
  StockIdRoute: typeof StockIdRoute
  StockIndexRoute: typeof StockIndexRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockIdRoute: StockIdRoute,
  StockIndexRoute: StockIndexRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashbookRoute: CashbookRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  KhataRoute: KhataRouteWithChildren,
  MoreRoute: MoreRoute,
  PurchasesRoute: PurchasesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
